import { ThemeProvider } from "@/components/providers/theme";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "NextJS + Bun + BiomeJS",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider attribute={"class"} enableSystem defaultTheme="light">
					<div className="flex w-full flex-col items-center pt-5">
						<Image
							src={"/logo.png"}
							alt="MOSC Logo"
							width={400}
							height={400}
							className="h-[80px] object-contain"
						/>
					</div>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
